mysql:
  host: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: gin_blog
  user: root
  password: "395621926"
  max-idle-conns: 0
  max-open-conns: 0
  log_level: dev
logger:
  level: info
  prefix: '[gin-blog-log]'
  director: log
  show_line: true
  log_in_console: true
system:
  env: release
  host: 0.0.0.0
  port: 8081
site_info:
  created_at: "2022-12-06"
  bei_an: 赣ICP备2021010654号-3
  title: 小黄个人博客
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/qq.png
  version: 6.0.1
  email: 2663456523@qq.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: 小黄知道
  job: 后端开发
  addr: 江西南昌
  slogan: 小黄知道了
  slogan_en: FENGFENGZHIDAO
  web: http://www.fengfengzhidao.com/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao/
upload:
  size: 2
  path: uploads/file
qi_niu:
  enable: true
  access_key: xLvqh1DGkeI3pW13hDcvaWcw5cBWqbzX1ooaYDod
  secret_key: QVmayh-610-ZE61q02w3SezUvvY6tpoRMx6hgyk5
  bucket: gin-blog-hws
  cdn: sdeu1ha62.hd-bkt.clouddn.com
  zone: z0
  prefix: gin_blog
  size: 5
