mysql:
  host: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: gateway
  username: root
  password: "395621926"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
logger:
  level: info
  prefix: '[gin-blog-log]'
  director: log
  show-line: true
  log-in-console: true
system:
  env: test
  ip: 0.0.0.0
  port: 8080
site-info:
  created_at: "2024-05-06"
  bei_an: 赣ICP备2021010654号-3
  title: 小黄个人博客
  qq_image: 1
  version: 6.0.1
  email: 2663456523@qq.com
  wechat_image: 1
  name: 小黄知道
  job: 后端开发
  addr: 江西南昌
  slogan: 小黄知道
  slogan_en: 1
  web: 1
  bilibili_url: 1
  gitee_url: 1
  github_url: 1
